In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from tensorflow.keras import layers
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
import pandas as pd

df = pd.DataFrame({
    "soil_moisture": [
        0.10, 0.15, 0.20, 0.25, 0.40, 0.60, 0.35, 0.18,
        0.45, 0.05, 0.80, 0.27, 0.55, 0.70, 0.12, 0.30
    ],

    "temperature_c": [
        34, 30, 26, 22, 28, 30, 19, 22,
        35, 24, 33, 33, 21, 25, 20, 29
    ],

    "sunlight_hours": [
        9, 8, 7, 4, 8, 10, 3, 10,
        12, 5, 9, 11, 2, 6, 1, 9
    ],

    "needs_water": [
        1, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 0, 0, 1, 1
    ]
})

print(df)

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df

    soil_moisture  temperature_c  sunlight_hours  needs_water
0            0.10             34               9            1
1            0.15             30               8            1
2            0.20             26               7            1
3            0.25             22               4            0
4            0.40             28               8            0
5            0.60             30              10            0
6            0.35             19               3            0
7            0.18             22              10            1
8            0.45             35              12            0
9            0.05             24               5            1
10           0.80             33               9            0
11           0.27             33              11            1
12           0.55             21               2            0
13           0.70             25               6            0
14           0.12             20               1            1
15           0.30             29               9            1

In [ ]:
df.columns

Index(['soil_moisture', 'temperature_c', 'sunlight_hours', 'needs_water'], dtype='object')

In [ ]:
x=df[['soil_moisture', 'temperature_c', 'sunlight_hours']]
y=df['needs_water']

In [ ]:
x_min=x.min()
x_max=x.max()
x_scaled = (x - x_min) / (x_max - x_min)

In [ ]:
x_scaled

    soil_moisture  temperature_c  sunlight_hours
0        0.066667         0.9375        0.727273
1        0.133333         0.6875        0.636364
2        0.200000         0.4375        0.545455
3        0.266667         0.1875        0.272727
4        0.466667         0.5625        0.636364
5        0.733333         0.6875        0.818182
6        0.400000         0.0000        0.181818
7        0.173333         0.1875        0.818182
8        0.533333         1.0000        1.000000
9        0.000000         0.3125        0.363636
10       1.000000         0.8750        0.727273
11       0.293333         0.8750        0.909091
12       0.666667         0.1250        0.090909
13       0.866667         0.3750        0.454545
14       0.093333         0.0625        0.000000
15       0.333333         0.6250        0.727273

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.33, random_state=42,stratify=y)

In [ ]:
model=keras.Sequential([
    layers.Input(shape=(X_train.shape[1],)),
    layers.Dense(10,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [ ]:
model.compile(optimizer='sgd',loss='binary_crossentropy',metrics=['accuracy'])

In [ ]:
history=model.fit(
    X_train.values,y_train.values,
    validation_data=(X_test.values,y_test.values),
    epochs=100,batch_size=4,verbose=1
)

Epoch 1/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 1s 113ms/step - accuracy: 0.4000 - loss: 1.8848 - val_accuracy: 0.5000 - val_loss: 2.4577
Epoch 2/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.5000 - loss: 1.9176 - val_accuracy: 0.5000 - val_loss: 1.7093
Epoch 3/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 1.4774 - val_accuracy: 0.3333 - val_loss: 1.0280
Epoch 4/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6428 - val_accuracy: 0.6667 - val_loss: 0.9654
Epoch 5/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3000 - loss: 1.5783 - val_accuracy: 0.6667 - val_loss: 0.9637
Epoch 6/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 0.7419 - val_accuracy: 0.6667 - val_loss: 0.9674
Epoch 7/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 1.1541 - val_accuracy: 0.5000 - val_loss: 1.7338
Epoch 8/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7000 - loss: 0.8620 - val_accuracy: 0.3333 - val_loss: 1.0070
Epoch 9/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 0.6223 - val_accuracy: 0.6667 - val_loss: 1.0588
Epoch 10/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 1.1844 - val_accuracy: 0.5000 - val_loss: 2.4733
Epoch 11/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.3000 - loss: 1.9266 - val_accuracy: 0.5000 - val_loss: 2.6215
Epoch 12/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 1.2312 - val_accuracy: 0.6667 - val_loss: 0.9701
Epoch 13/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7578 - val_accuracy: 0.5000 - val_loss: 1.6967
Epoch 14/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3000 - loss: 1.7427 - val_accuracy: 0.5000 - val_loss: 1.8017
Epoch 15/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 1.5633 - val_accuracy: 0.6667 - val_loss: 0.9162
Epoch 16/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.9535 - val_accuracy: 0.5000 - val_loss: 2.0513
Epoch 17/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3000 - loss: 1.2995 - val_accuracy: 0.5000 - val_loss: 1.1250
Epoch 18/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.4000 - loss: 1.0228 - val_accuracy: 0.5000 - val_loss: 1.6310
Epoch 19/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.9141 - val_accuracy: 0.3333 - val_loss: 0.9945
Epoch 20/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.4000 - loss: 0.8607 - val_accuracy: 0.5000 - val_loss: 1.1675
Epoch 21/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.7000 - loss: 0.7260 - val_accuracy: 0.3333 - val_loss: 1.0123
Epoch 22/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.7296 - val_accuracy: 0.5000 - val_loss: 1.1806
Epoch 23/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.8114 - val_accuracy: 0.5000 - val_loss: 1.0513
Epoch 24/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 0.6546 - val_accuracy: 0.6667 - val_loss: 0.8928
Epoch 25/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6799 - val_accuracy: 0.3333 - val_loss: 0.9157
Epoch 26/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.8080 - val_accuracy: 0.5000 - val_loss: 1.0507
Epoch 27/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 0.8040 - val_accuracy: 0.5000 - val_loss: 1.5825
Epoch 28/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.9809 - val_accuracy: 0.6667 - val_loss: 0.8493
Epoch 29/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7292 - val_accuracy: 0.6667 - val_loss: 0.8567
Epoch 30/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6818 - val_accuracy: 0.6667 - val_loss: 0.8498
Epoch 31/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.7000 - loss: 0.6725 - val_accuracy: 0.3333 - val_loss: 0.8640
Epoch 32/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3000 - loss: 0.9524 - val_accuracy: 0.5000 - val_loss: 1.0392
Epoch 33/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.8011 - val_accuracy: 0.3333 - val_loss: 0.8702
Epoch 34/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.6892 - val_accuracy: 0.3333 - val_loss: 0.8701
Epoch 35/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.6000 - loss: 0.6826 - val_accuracy: 0.6667 - val_loss: 0.8312
Epoch 36/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.7114 - val_accuracy: 0.5000 - val_loss: 1.2057
Epoch 37/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.9317 - val_accuracy: 0.5000 - val_loss: 1.0173
Epoch 38/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.7195 - val_accuracy: 0.3333 - val_loss: 0.8498
Epoch 39/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.7324 - val_accuracy: 0.6667 - val_loss: 0.8163
Epoch 40/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7000 - loss: 0.6694 - val_accuracy: 0.5000 - val_loss: 1.0800
Epoch 41/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - accuracy: 0.5000 - loss: 0.8231 - val_accuracy: 0.3333 - val_loss: 0.8633
Epoch 42/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6547 - val_accuracy: 0.3333 - val_loss: 0.8646
Epoch 43/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6701 - val_accuracy: 0.6667 - val_loss: 0.8155
Epoch 44/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.3000 - loss: 0.8082 - val_accuracy: 0.5000 - val_loss: 0.8992
Epoch 45/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7499 - val_accuracy: 0.3333 - val_loss: 0.8551
Epoch 46/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.7056 - val_accuracy: 0.6667 - val_loss: 0.8103
Epoch 47/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7106 - val_accuracy: 0.6667 - val_loss: 0.7926
Epoch 48/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.3000 - loss: 0.8866 - val_accuracy: 0.5000 - val_loss: 0.8332
Epoch 49/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 0.8108 - val_accuracy: 0.6667 - val_loss: 0.8085
Epoch 50/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.4000 - loss: 0.7486 - val_accuracy: 0.6667 - val_loss: 0.7850
Epoch 51/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6441 - val_accuracy: 0.3333 - val_loss: 0.8290
Epoch 52/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 0.7128 - val_accuracy: 0.5000 - val_loss: 0.9153
Epoch 53/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.8047 - val_accuracy: 0.5000 - val_loss: 0.8713
Epoch 54/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.7336 - val_accuracy: 0.5000 - val_loss: 0.9590
Epoch 55/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 39ms/step - accuracy: 0.4000 - loss: 0.8112 - val_accuracy: 0.5000 - val_loss: 0.8624
Epoch 56/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6863 - val_accuracy: 0.6667 - val_loss: 0.7804
Epoch 57/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.7166 - val_accuracy: 0.3333 - val_loss: 0.8377
Epoch 58/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 0.6716 - val_accuracy: 0.6667 - val_loss: 0.7775
Epoch 59/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7042 - val_accuracy: 0.6667 - val_loss: 0.7995
Epoch 60/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.5000 - loss: 0.7101 - val_accuracy: 0.6667 - val_loss: 0.7736
Epoch 61/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6544 - val_accuracy: 0.6667 - val_loss: 0.7785
Epoch 62/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.7000 - loss: 0.6830 - val_accuracy: 0.3333 - val_loss: 0.7985
Epoch 63/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.7000 - loss: 0.6422 - val_accuracy: 0.3333 - val_loss: 0.7889
Epoch 64/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6694 - val_accuracy: 0.5000 - val_loss: 0.8843
Epoch 65/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.7134 - val_accuracy: 0.3333 - val_loss: 0.8428
Epoch 66/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step - accuracy: 0.5000 - loss: 0.7351 - val_accuracy: 0.5000 - val_loss: 0.9118
Epoch 67/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.6000 - loss: 0.6991 - val_accuracy: 0.3333 - val_loss: 0.7796
Epoch 68/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4000 - loss: 0.7865 - val_accuracy: 0.6667 - val_loss: 0.7719
Epoch 69/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6801 - val_accuracy: 0.3333 - val_loss: 0.7748
Epoch 70/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.4000 - loss: 0.7422 - val_accuracy: 0.5000 - val_loss: 0.8745
Epoch 71/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6690 - val_accuracy: 0.3333 - val_loss: 0.7740
Epoch 72/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 0.6904 - val_accuracy: 0.6667 - val_loss: 0.7666
Epoch 73/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.4000 - loss: 0.7039 - val_accuracy: 0.3333 - val_loss: 0.7802
Epoch 74/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - accuracy: 0.7000 - loss: 0.6723 - val_accuracy: 0.6667 - val_loss: 0.7647
Epoch 75/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - accuracy: 0.5000 - loss: 0.6582 - val_accuracy: 0.3333 - val_loss: 0.7863
Epoch 76/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.7000 - loss: 0.6488 - val_accuracy: 0.3333 - val_loss: 0.8099
Epoch 77/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - accuracy: 0.6000 - loss: 0.6750 - val_accuracy: 0.6667 - val_loss: 0.7661
Epoch 78/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.5000 - loss: 0.6748 - val_accuracy: 0.5000 - val_loss: 0.8776
Epoch 79/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - accuracy: 0.6000 - loss: 0.7376 - val_accuracy: 0.5000 - val_loss: 0.9069
Epoch 80/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - accuracy: 0.6000 - loss: 0.8155 - val_accuracy: 0.5000 - val_loss: 0.8391
Epoch 81/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - accuracy: 0.4000 - loss: 0.7148 - val_accuracy: 0.5000 - val_loss: 0.8592
Epoch 82/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - accuracy: 0.6000 - loss: 0.6997 - val_accuracy: 0.6667 - val_loss: 0.7548
Epoch 83/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 41ms/step - accuracy: 0.6000 - loss: 0.6680 - val_accuracy: 0.3333 - val_loss: 0.7637
Epoch 84/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.4000 - loss: 0.6736 - val_accuracy: 0.6667 - val_loss: 0.7575
Epoch 85/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.4000 - loss: 0.7337 - val_accuracy: 0.6667 - val_loss: 0.7692
Epoch 86/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.7469 - val_accuracy: 0.6667 - val_loss: 0.7541
Epoch 87/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step - accuracy: 0.6000 - loss: 0.6745 - val_accuracy: 0.6667 - val_loss: 0.7500
Epoch 88/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6741 - val_accuracy: 0.6667 - val_loss: 0.7500
Epoch 89/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.6599 - val_accuracy: 0.6667 - val_loss: 0.7514
Epoch 90/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step - accuracy: 0.6000 - loss: 0.6699 - val_accuracy: 0.6667 - val_loss: 0.7523
Epoch 91/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6516 - val_accuracy: 0.3333 - val_loss: 0.7553
Epoch 92/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6702 - val_accuracy: 0.6667 - val_loss: 0.7527
Epoch 93/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - accuracy: 0.7000 - loss: 0.6538 - val_accuracy: 0.3333 - val_loss: 0.7607
Epoch 94/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.5000 - loss: 0.7606 - val_accuracy: 0.3333 - val_loss: 0.7614
Epoch 95/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.6000 - loss: 0.6623 - val_accuracy: 0.3333 - val_loss: 0.8014
Epoch 96/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.6767 - val_accuracy: 0.3333 - val_loss: 0.7789
Epoch 97/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step - accuracy: 0.5000 - loss: 0.6743 - val_accuracy: 0.6667 - val_loss: 0.7529
Epoch 98/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 38ms/step - accuracy: 0.5000 - loss: 0.7515 - val_accuracy: 0.5000 - val_loss: 0.8051
Epoch 99/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 37ms/step - accuracy: 0.5000 - loss: 0.6952 - val_accuracy: 0.5000 - val_loss: 0.8358
Epoch 100/100
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 36ms/step - accuracy: 0.6000 - loss: 0.7143 - val_accuracy: 0.3333 - val_loss: 0.7786